### PR TITLE
Header and footer

### PR DESCRIPTION
**Pull request by tamsay**
The header and footer components of the netflix clone task. Kindly review and revert. Thank you

### CODE REVIEW

**Comment by tamsay** [comment]
kindly review and revert. thank you

**Comment by neymarjimoh** [comment]
Fix your conflicts

**Comment by tamsay** [comment]
Conflicts resolved. Kindly review. Thank you

**Comment by hadeelsala7** [comment]
Hi
This branch didn't follow the rules,
First of all, you must create the branch from "develop branch" not From MASTER
Second don't merge anything u want, the structure is already ready in branch called "develop branch"
Third, DON'T CHANGE ANYTHING WITHOUT PERMISSION!!!

**Pull request merged**
